import type { CompareResult, ModelId } from '../core/types.js';
import { tokenizeText } from '../tokenizers/registry.js';

const HTML_PALETTE = [
  '#3b82f6',
  '#a855f7',
  '#06b6d4',
  '#22c55e',
  '#eab308',
  '#ef4444',
  '#ec4899',
  '#f97316',
];

export async function formatHtml(text: string, results: CompareResult[]): Promise<string> {
  const vizModel: ModelId = (results.find((r) => r.accuracy === 'exact')?.model ??
    results[0]?.model ??
    'gpt-4o') as ModelId;
  const viz = await tokenizeText(text, vizModel);

  const tableRows = results
    .map((r) => {
      const cls = r.accuracy === 'exact' ? 'exact' : 'approx';
      return `      <tr>
        <td><code>${escapeHtml(r.model)}</code></td>
        <td>${r.tokens}</td>
        <td>${r.charsPerToken.toFixed(2)}</td>
        <td>${formatCost(r)}</td>
        <td>${formatPct(r.contextUsedPct)}</td>
        <td><span class="acc ${cls}">${r.accuracy}</span></td>
      </tr>`;
    })
    .join('\n');

  const tokenSpans = viz.pieces
    .map((p, i) => {
      const color = HTML_PALETTE[i % HTML_PALETTE.length] ?? '#888888';
      return `<span class="tok" style="background:${color}1a;border-bottom:2px solid ${color}" title="id: ${viz.ids[i]}">${escapeHtml(visible(p))}</span>`;
    })
    .join('');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>llm-token-compare</title>
<style>
  body { font: 14px ui-sans-serif, system-ui, sans-serif; max-width: 880px; margin: 2.5rem auto; padding: 0 1.5rem; color: #111827; background: #fafafa; }
  h1 { font-size: 1.5rem; margin: 0 0 0.25rem; }
  h2 { font-size: 1rem; margin: 1.75rem 0 0.5rem; color: #374151; }
  .sub { color: #6b7280; margin: 0 0 1.5rem; }
  table { border-collapse: collapse; width: 100%; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.04); }
  th, td { padding: 0.6rem 0.85rem; text-align: left; border-bottom: 1px solid #f1f5f9; }
  th { background: #f9fafb; font-weight: 600; font-size: 0.85rem; color: #4b5563; text-transform: uppercase; letter-spacing: 0.04em; }
  tr:last-child td { border-bottom: none; }
  code { font-family: ui-monospace, monospace; font-size: 0.92em; }
  .acc { font-size: 0.78rem; padding: 2px 8px; border-radius: 999px; font-weight: 500; }
  .acc.exact { background: #dcfce7; color: #166534; }
  .acc.approx { background: #fef3c7; color: #92400e; }
  .viz { background: #fff; padding: 1rem; border-radius: 8px; line-height: 1.9; word-break: break-word; box-shadow: 0 1px 3px rgba(0,0,0,0.04); font-family: ui-monospace, monospace; font-size: 0.9rem; }
  .tok { padding: 1px 2px; border-radius: 3px; }
  .meta { color: #6b7280; font-size: 0.85rem; margin-top: 0.75rem; }
  footer { margin-top: 2.5rem; color: #9ca3af; font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
  <h1>llm-token-compare</h1>
  <p class="sub">${results.length} models · ${[...text].length} characters</p>

  <h2>Costs &amp; counts</h2>
  <table>
    <thead>
      <tr><th>Model</th><th>Tokens</th><th>c/tok</th><th>$/1k</th><th>ctx%</th><th>Accuracy</th></tr>
    </thead>
    <tbody>
${tableRows}
    </tbody>
  </table>

  <h2>Tokenization (${escapeHtml(vizModel)})</h2>
  <div class="viz">${tokenSpans}</div>
  <p class="meta">Each colored block is one token. Hover for token id.</p>

  <footer>Generated by <code>llm-token-compare</code></footer>
</body>
</html>
`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function visible(s: string): string {
  return s.replace(/\n/g, '⏎\n').replace(/\t/g, '→') || '·';
}

function formatCost(r: CompareResult): string {
  if (r.selfHosted) return 'local';
  if (r.costPer1kCalls === 0) return '$0';
  if (r.costPer1kCalls < 0.01) return `$${r.costPer1kCalls.toFixed(4)}`;
  if (r.costPer1kCalls < 1) return `$${r.costPer1kCalls.toFixed(3)}`;
  return `$${r.costPer1kCalls.toFixed(2)}`;
}

function formatPct(p: number): string {
  if (p < 0.01) return `${p.toFixed(4)}%`;
  if (p < 1) return `${p.toFixed(2)}%`;
  return `${p.toFixed(1)}%`;
}
